FROM ubuntu:latest

MAINTAINER ayavorsk

RUN apt update
RUN apt upgrade -y
RUN apt install curl -y
RUN apt install clang -y
RUN apt install build-essential -y
RUN apt install git-core -y
RUN apt install wget -y
RUN apt install gcc -y
RUN apt install emacs -y
RUN apt install vim -y
